### ISSUE TITLE
Game Launcher Launch Error 2.0.0.19

### ISSUE THREAD

**Issue by 1DavidCarbon** [SoapboxRaceWorld/GameLauncher_NFSW#133]
- **Launcher Version:** 2.0.0.19
- **Operating system:** Windows 10 Home
- **Antivirus/Firewall (if any):** No Firewall or Antivirus (Yoloing it all the way)
```
Application does not support just-in-time (JIT)
debugging. See the end of this message for details.

************** Exception Text **************
System.BadImageFormatException: An attempt was made to load a program with an incorrect format. (Exception from HRESULT: 0x8007000B)
   at DiscordRPC.DiscordRpc.Initialize(String applicationId, EventHandlers& handlers, Boolean autoRegister, String optionalSteamId)
   at GameLauncher.MainScreen..ctor(Form splashscreen)
   at GameLauncher.Program.Main()


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3221.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
GameLauncher
    Assembly Version: 2.0.0.1195
    Win32 Version: 2.0.0.19
    CodeBase: file:///C:/Soapbox%20Race%20World/Release(4)/GameLauncher.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3221.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3190.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
INIFileParser
    Assembly Version: 2.5.2.0
    Win32 Version: 2.5.2
    CodeBase: file:///C:/Soapbox%20Race%20World/Release(4)/INIFileParser.DLL
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3221.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Nancy.Hosting.Self
    Assembly Version: 1.4.1.0
    Win32 Version: 1.4.1.0
    CodeBase: file:///C:/Soapbox%20Race%20World/Release(4)/Nancy.Hosting.Self.DLL
----------------------------------------
Nancy
    Assembly Version: 1.4.4.0
    Win32 Version: 1.4.4.0
    CodeBase: file:///C:/Soapbox%20Race%20World/Release(4)/Nancy.DLL
----------------------------------------
Anonymously Hosted DynamicMethods Assembly
    Assembly Version: 0.0.0.0
    Win32 Version: 4.7.3221.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
----------------------------------------
Microsoft.CSharp
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
----------------------------------------
System.Dynamic
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
----------------------------------------
Bugsnag
    Assembly Version: 2.2.0.0
    Win32 Version: 2.2.0.0
    CodeBase: file:///C:/Soapbox%20Race%20World/Release(4)/Bugsnag.DLL
----------------------------------------

************** JIT Debugging **************
Application does not support Windows Forms just-in-time (JIT)
debugging. Contact the application author for more
information.
```
![Image of Launcher](https://lh3.googleusercontent.com/aLPvTlHH8Ge3ZFD8O2Hd0Q9-sBRBgr7_JnsICIJAC4upl8ud9zUGyL4vkurZNZ5_pmTr5AEgsoX7xU9ZtZBa6_lIzSHZ-uAw0-tIuffwPjiNkDYPzMl57cZaEP4kPmOHidEKoyWY01cCu_DI_jh7ZzgNBkivg6Hwibfi-uVZYNnDnV2XvZBGlw_bYsoHFQ9klYw6_3EmF7AsOKBSa_vyY0Wkt8uCnguXHJifwpLxIgOU76C0coDyZ1hD3u0ntAg8POW1erVeh7cxLhHpmyGxRuJjK6HYUoe-cx2wT4LC-0E-4aPmPSQbfOlZd5sGOpSEpCTV1lezYUQMqUPRJV0Iwlhz7AxDBjySuSI_YuGBvuIzbwC_1LoGitPPjGQgyjx8s7hf7lPNqmT7kqVbMOo3lmHFMMO7dg6im6zg81hnOkJaQz--M_haLSXBwrsRHE7LonwRWXWLMqHfzreel3y648KvZL5ot7ldXI_m29PXn0uhd4qYyHpAthFFMScfbmX9tOFtW1oxSQO356dhMuwf-_sJ41SiA4Q8KfBzuaOJSlXxXuaNzIVeW5k7jOAuPZxLkgt5T3iPp9YTWCoNk-7tHYWpPwOUU0Fd1ZUKO99pUfazgX8B7H9lkc4631PrOljLja4u4hB_uclf2cBTw0gPQros=w439-h339-no)

**Comment by metonator** [comment]
UPDATE: Launcher were compiled using x64 compiler instead of x86.
