### ISSUE TITLE
Unable to login and therefore cannot get past the launcher

### ISSUE THREAD

**Issue by BoomYaf** [SoapboxRaceWorld/GameLauncher_NFSW#256]
- **Launcher Version:** 2.2.2
- **Operating system:** Windows 10 Home
- **Antivirus/Firewall (if any):** None
- **Wine/Mono Version (if any):** Don't know

I get this error when I try to login to the World United server but not for NightRiderz server: 
[      ERROR] XML LOGIN: 'doctype' is an unexpected token. The expected token is 'DOCTYPE'. Line 1, position 3.

What am I supposed to do?
This is the full log of the error that happens after I click "Login":

06/10/2023 [ ERROR CODE] XML LOGIN: -2146232000
06/10/2023 [ FULL ERROR] XML LOGIN: System.Xml.XmlException: 'doctype' is an unexpected token. The expected token is 'DOCTYPE'. Line 1, position 3.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.Throw(String res, String[] args)
   at System.Xml.XmlTextReaderImpl.ThrowUnexpectedToken(String expectedToken1, String expectedToken2)
   at System.Xml.XmlTextReaderImpl.ParseDoctypeDecl()
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.LoadXml(String xml)
   at SBRW.Launcher.RunTime.LauncherCore.Client.Auth.Authentication.Client(String Method, Boolean Modern_Auth, String Email, String Password, String Token) in G:\GitHub\SoapboxRaceWorld\GameLauncher_NFSW\SBRW.Launcher.RunTime\LauncherCore\Client\Auth\Authentication.cs:line 152
06/10/2023 [      ERROR] Authentication: Unable to Read XML File -> An error occured: 'doctype' is an unexpected token. The expected token is 'DOCTYPE'. Line 1, position 3.

**Comment by salviacode** [comment]
same thing windows 11, not sure bout console tho

**Comment by Darkshock25** [comment]
If you’re getting the SBRW / WorldUnited 'doctype' is an unexpected token error, here’s what actually fixed it for me.
The short version:
The problem wasn’t my PC or the launcher. It was my ISP/modem corrupting the login data. Using a VPN forced a clean route and the error disappeared instantly.
Here’s the full step‑by‑step:

✅ Step 1: Install and open ProtonVPN (or any VPN)
- Download and install ProtonVPN (free plan works)
- Open ProtonVPN
- Log in or create a free account
(Any VPN works, but these steps are written for ProtonVPN.)

✅ Step 2: Connect to a good server
- In ProtonVPN, pick a United States server
- Prefer servers like:
- US‑NY (New York)
- US‑VA (Virginia)
- US‑IL (Illinois)
- US‑TX (Texas)
- Avoid servers that are red or above 80% load
- Click the server to connect
- Wait until ProtonVPN shows “Connected” with a green icon

✅ Step 3: Make sure the VPN is actually working
- Open your browser
- Go to:
- https://whatismyip.com
- Check that your IP address is different from your normal one
- If it’s the same, switch to another ProtonVPN server and try again

✅ Step 4: Launch the game in the correct order
This order matters.
- Close the SBRW launcher completely
(Make sure it’s not running in the tray)
- Connect ProtonVPN
- Once the VPN is connected, then open the SBRW launcher
- Log in normally
If your ISP/modem was altering the login headers, the 'doctype' error will disappear immediately.

Hope that helps. My CoPilot gave me the answer after founding out using a VPN being a reliable method if the connection fails.
